### ISSUE TITLE
The mapping itself

### ISSUE THREAD

**Issue by ghost** [geo4web-testbed/simpleBAG-to-schemaorg#2]
[bag_mapping.xlsx](https://github.com/geo4web-testbed/simpleBAG-to-schemaorg/files/48696/bag_mapping.xlsx)

**Comment by cportele** [comment]
@liekeverhelst 
Thanks. Any thoughts, if we should add any of the following? 
- add schema:postalCode also to the GeoCoordinates
- add schema:addressCountry as a fixed value to PostalAddress and/or GeoCoordinates

Not sure, if there would be any benefits...

**Comment by ghost** [comment]
@cportele, yes we could do this, the schema.org's domain/range specs for these properties allow this. You mean as a text value (you mention "fixed" value)? This is indeed possible.
What would be the benefit..it is kind of adding redundant data..but by doing this we could profit from any nice features that the search engines plan to project on both the classes PostalAddress and GeoCoordinates.
I have noticed while working on this that here's a lot to say about the mapping. I will discuss this with you and @pvgenuchten and report on Github our findings.

**Comment by cportele** [comment]
@liekeverhelst, I have added another JSON-LD file that is slightly different in the way the BAG feature is encoded. I am not entirely sure about the pros and cons for each approach. However, for me Place is the right schema.org type for the feature.

https://developers.google.com/structured-data/testing-tool/ complains about the array in @context, but I do not understand why.

**Comment by ghost** [comment]
@cportele I changed the syntax a bit, now it validates fine. Which approach we take is all semantics..what is documented in the data, is that a Place or a PostalAddress? I like your version better than mine..;-). A PostalAddress is too narrow a description.

**Comment by ghost** [comment]
Hold on..I made a mistake with the contexts..will fix it now

**Comment by cportele** [comment]
Thanks.

I think Place is more appropriate and represents that fact that this is a feature. PostalAddress and GeoCoordinates are "just" StructuredValues that are used to describe things. This is at least how I read schema.org.

**Comment by cportele** [comment]
@liekeverhelst @pvgenuchten I have updated the example and also included resources for the dataset and feature type landing pages for our discussion. I don't think this would work well yet, but it has the main information included that we need including most of the links.

**Comment by ghost** [comment]
@cportele : FYI it looks like the structured data validator does not like it when you attach two types to one URI.  .so a Dataset cannot be a hydra:Class at the same time...  
I have made new examples for feature, layer and landingpage in "clean" schema.org
